# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mimisk_bridge_pb2 as mimisk__bridge__pb2


class MIMISKBridgeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/Ping',
        request_serializer=mimisk__bridge__pb2.PingRequest.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.PingReply.FromString,
        )
    self.SendTelemetry = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/SendTelemetry',
        request_serializer=mimisk__bridge__pb2.MIMISKTelemetryFrame.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.TelemetryAck.FromString,
        )
    self.SendCameraFrame = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/SendCameraFrame',
        request_serializer=mimisk__bridge__pb2.CameraFrame.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.TelemetryAck.FromString,
        )
    self.GetPendingCommands = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/GetPendingCommands',
        request_serializer=mimisk__bridge__pb2.CommandBatchRequest.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.CommandBatch.FromString,
        )
    self.GetManualControls = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/GetManualControls',
        request_serializer=mimisk__bridge__pb2.ManualControlRequest.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.ManualControlBatch.FromString,
        )
    self.GetExternalReferences = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/GetExternalReferences',
        request_serializer=mimisk__bridge__pb2.ExternalReferenceRequest.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.ExternalReferenceBatch.FromString,
        )
    self.ReportCommandResult = channel.unary_unary(
        '/mimisk.bridge.MIMISKBridge/ReportCommandResult',
        request_serializer=mimisk__bridge__pb2.CommandExecutionResult.SerializeToString,
        response_deserializer=mimisk__bridge__pb2.TelemetryAck.FromString,
        )


class MIMISKBridgeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTelemetry(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCameraFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPendingCommands(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetManualControls(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExternalReferences(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportCommandResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MIMISKBridgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=mimisk__bridge__pb2.PingRequest.FromString,
          response_serializer=mimisk__bridge__pb2.PingReply.SerializeToString,
      ),
      'SendTelemetry': grpc.unary_unary_rpc_method_handler(
          servicer.SendTelemetry,
          request_deserializer=mimisk__bridge__pb2.MIMISKTelemetryFrame.FromString,
          response_serializer=mimisk__bridge__pb2.TelemetryAck.SerializeToString,
      ),
      'SendCameraFrame': grpc.unary_unary_rpc_method_handler(
          servicer.SendCameraFrame,
          request_deserializer=mimisk__bridge__pb2.CameraFrame.FromString,
          response_serializer=mimisk__bridge__pb2.TelemetryAck.SerializeToString,
      ),
      'GetPendingCommands': grpc.unary_unary_rpc_method_handler(
          servicer.GetPendingCommands,
          request_deserializer=mimisk__bridge__pb2.CommandBatchRequest.FromString,
          response_serializer=mimisk__bridge__pb2.CommandBatch.SerializeToString,
      ),
      'GetManualControls': grpc.unary_unary_rpc_method_handler(
          servicer.GetManualControls,
          request_deserializer=mimisk__bridge__pb2.ManualControlRequest.FromString,
          response_serializer=mimisk__bridge__pb2.ManualControlBatch.SerializeToString,
      ),
      'GetExternalReferences': grpc.unary_unary_rpc_method_handler(
          servicer.GetExternalReferences,
          request_deserializer=mimisk__bridge__pb2.ExternalReferenceRequest.FromString,
          response_serializer=mimisk__bridge__pb2.ExternalReferenceBatch.SerializeToString,
      ),
      'ReportCommandResult': grpc.unary_unary_rpc_method_handler(
          servicer.ReportCommandResult,
          request_deserializer=mimisk__bridge__pb2.CommandExecutionResult.FromString,
          response_serializer=mimisk__bridge__pb2.TelemetryAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mimisk.bridge.MIMISKBridge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
