// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mimisk_bridge.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MIMISK.Grpc {
  public static partial class MIMISKBridge
  {
    static readonly string __ServiceName = "mimisk.bridge.MIMISKBridge";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.PingRequest> __Marshaller_mimisk_bridge_PingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.PingRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.PingReply> __Marshaller_mimisk_bridge_PingReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.PingReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.MIMISKTelemetryFrame> __Marshaller_mimisk_bridge_MIMISKTelemetryFrame = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.MIMISKTelemetryFrame.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.TelemetryAck> __Marshaller_mimisk_bridge_TelemetryAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.TelemetryAck.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.CameraFrame> __Marshaller_mimisk_bridge_CameraFrame = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.CameraFrame.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.CommandBatchRequest> __Marshaller_mimisk_bridge_CommandBatchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.CommandBatchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.CommandBatch> __Marshaller_mimisk_bridge_CommandBatch = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.CommandBatch.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.ManualControlRequest> __Marshaller_mimisk_bridge_ManualControlRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.ManualControlRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.ManualControlBatch> __Marshaller_mimisk_bridge_ManualControlBatch = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.ManualControlBatch.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.ExternalReferenceRequest> __Marshaller_mimisk_bridge_ExternalReferenceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.ExternalReferenceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.ExternalReferenceBatch> __Marshaller_mimisk_bridge_ExternalReferenceBatch = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.ExternalReferenceBatch.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MIMISK.Grpc.CommandExecutionResult> __Marshaller_mimisk_bridge_CommandExecutionResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MIMISK.Grpc.CommandExecutionResult.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.PingRequest, global::MIMISK.Grpc.PingReply> __Method_Ping = new grpc::Method<global::MIMISK.Grpc.PingRequest, global::MIMISK.Grpc.PingReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_mimisk_bridge_PingRequest,
        __Marshaller_mimisk_bridge_PingReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.MIMISKTelemetryFrame, global::MIMISK.Grpc.TelemetryAck> __Method_SendTelemetry = new grpc::Method<global::MIMISK.Grpc.MIMISKTelemetryFrame, global::MIMISK.Grpc.TelemetryAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendTelemetry",
        __Marshaller_mimisk_bridge_MIMISKTelemetryFrame,
        __Marshaller_mimisk_bridge_TelemetryAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.CameraFrame, global::MIMISK.Grpc.TelemetryAck> __Method_SendCameraFrame = new grpc::Method<global::MIMISK.Grpc.CameraFrame, global::MIMISK.Grpc.TelemetryAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendCameraFrame",
        __Marshaller_mimisk_bridge_CameraFrame,
        __Marshaller_mimisk_bridge_TelemetryAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.CommandBatchRequest, global::MIMISK.Grpc.CommandBatch> __Method_GetPendingCommands = new grpc::Method<global::MIMISK.Grpc.CommandBatchRequest, global::MIMISK.Grpc.CommandBatch>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPendingCommands",
        __Marshaller_mimisk_bridge_CommandBatchRequest,
        __Marshaller_mimisk_bridge_CommandBatch);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.ManualControlRequest, global::MIMISK.Grpc.ManualControlBatch> __Method_GetManualControls = new grpc::Method<global::MIMISK.Grpc.ManualControlRequest, global::MIMISK.Grpc.ManualControlBatch>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetManualControls",
        __Marshaller_mimisk_bridge_ManualControlRequest,
        __Marshaller_mimisk_bridge_ManualControlBatch);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.ExternalReferenceRequest, global::MIMISK.Grpc.ExternalReferenceBatch> __Method_GetExternalReferences = new grpc::Method<global::MIMISK.Grpc.ExternalReferenceRequest, global::MIMISK.Grpc.ExternalReferenceBatch>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetExternalReferences",
        __Marshaller_mimisk_bridge_ExternalReferenceRequest,
        __Marshaller_mimisk_bridge_ExternalReferenceBatch);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MIMISK.Grpc.CommandExecutionResult, global::MIMISK.Grpc.TelemetryAck> __Method_ReportCommandResult = new grpc::Method<global::MIMISK.Grpc.CommandExecutionResult, global::MIMISK.Grpc.TelemetryAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReportCommandResult",
        __Marshaller_mimisk_bridge_CommandExecutionResult,
        __Marshaller_mimisk_bridge_TelemetryAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MIMISK.Grpc.MimiskBridgeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MIMISKBridge</summary>
    [grpc::BindServiceMethod(typeof(MIMISKBridge), "BindService")]
    public abstract partial class MIMISKBridgeBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.PingReply> Ping(global::MIMISK.Grpc.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.TelemetryAck> SendTelemetry(global::MIMISK.Grpc.MIMISKTelemetryFrame request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.TelemetryAck> SendCameraFrame(global::MIMISK.Grpc.CameraFrame request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.CommandBatch> GetPendingCommands(global::MIMISK.Grpc.CommandBatchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.ManualControlBatch> GetManualControls(global::MIMISK.Grpc.ManualControlRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.ExternalReferenceBatch> GetExternalReferences(global::MIMISK.Grpc.ExternalReferenceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MIMISK.Grpc.TelemetryAck> ReportCommandResult(global::MIMISK.Grpc.CommandExecutionResult request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MIMISKBridge</summary>
    public partial class MIMISKBridgeClient : grpc::ClientBase<MIMISKBridgeClient>
    {
      /// <summary>Creates a new client for MIMISKBridge</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MIMISKBridgeClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MIMISKBridge that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MIMISKBridgeClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MIMISKBridgeClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MIMISKBridgeClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.PingReply Ping(global::MIMISK.Grpc.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.PingReply Ping(global::MIMISK.Grpc.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.PingReply> PingAsync(global::MIMISK.Grpc.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.PingReply> PingAsync(global::MIMISK.Grpc.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck SendTelemetry(global::MIMISK.Grpc.MIMISKTelemetryFrame request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendTelemetry(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck SendTelemetry(global::MIMISK.Grpc.MIMISKTelemetryFrame request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendTelemetry, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> SendTelemetryAsync(global::MIMISK.Grpc.MIMISKTelemetryFrame request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendTelemetryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> SendTelemetryAsync(global::MIMISK.Grpc.MIMISKTelemetryFrame request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendTelemetry, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck SendCameraFrame(global::MIMISK.Grpc.CameraFrame request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCameraFrame(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck SendCameraFrame(global::MIMISK.Grpc.CameraFrame request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendCameraFrame, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> SendCameraFrameAsync(global::MIMISK.Grpc.CameraFrame request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCameraFrameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> SendCameraFrameAsync(global::MIMISK.Grpc.CameraFrame request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendCameraFrame, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.CommandBatch GetPendingCommands(global::MIMISK.Grpc.CommandBatchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPendingCommands(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.CommandBatch GetPendingCommands(global::MIMISK.Grpc.CommandBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPendingCommands, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.CommandBatch> GetPendingCommandsAsync(global::MIMISK.Grpc.CommandBatchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPendingCommandsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.CommandBatch> GetPendingCommandsAsync(global::MIMISK.Grpc.CommandBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPendingCommands, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.ManualControlBatch GetManualControls(global::MIMISK.Grpc.ManualControlRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetManualControls(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.ManualControlBatch GetManualControls(global::MIMISK.Grpc.ManualControlRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetManualControls, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.ManualControlBatch> GetManualControlsAsync(global::MIMISK.Grpc.ManualControlRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetManualControlsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.ManualControlBatch> GetManualControlsAsync(global::MIMISK.Grpc.ManualControlRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetManualControls, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.ExternalReferenceBatch GetExternalReferences(global::MIMISK.Grpc.ExternalReferenceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalReferences(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.ExternalReferenceBatch GetExternalReferences(global::MIMISK.Grpc.ExternalReferenceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetExternalReferences, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.ExternalReferenceBatch> GetExternalReferencesAsync(global::MIMISK.Grpc.ExternalReferenceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalReferencesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.ExternalReferenceBatch> GetExternalReferencesAsync(global::MIMISK.Grpc.ExternalReferenceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetExternalReferences, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck ReportCommandResult(global::MIMISK.Grpc.CommandExecutionResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReportCommandResult(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::MIMISK.Grpc.TelemetryAck ReportCommandResult(global::MIMISK.Grpc.CommandExecutionResult request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReportCommandResult, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> ReportCommandResultAsync(global::MIMISK.Grpc.CommandExecutionResult request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReportCommandResultAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::MIMISK.Grpc.TelemetryAck> ReportCommandResultAsync(global::MIMISK.Grpc.CommandExecutionResult request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReportCommandResult, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MIMISKBridgeClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MIMISKBridgeClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MIMISKBridgeBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping)
          .AddMethod(__Method_SendTelemetry, serviceImpl.SendTelemetry)
          .AddMethod(__Method_SendCameraFrame, serviceImpl.SendCameraFrame)
          .AddMethod(__Method_GetPendingCommands, serviceImpl.GetPendingCommands)
          .AddMethod(__Method_GetManualControls, serviceImpl.GetManualControls)
          .AddMethod(__Method_GetExternalReferences, serviceImpl.GetExternalReferences)
          .AddMethod(__Method_ReportCommandResult, serviceImpl.ReportCommandResult).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MIMISKBridgeBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.PingRequest, global::MIMISK.Grpc.PingReply>(serviceImpl.Ping));
      serviceBinder.AddMethod(__Method_SendTelemetry, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.MIMISKTelemetryFrame, global::MIMISK.Grpc.TelemetryAck>(serviceImpl.SendTelemetry));
      serviceBinder.AddMethod(__Method_SendCameraFrame, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.CameraFrame, global::MIMISK.Grpc.TelemetryAck>(serviceImpl.SendCameraFrame));
      serviceBinder.AddMethod(__Method_GetPendingCommands, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.CommandBatchRequest, global::MIMISK.Grpc.CommandBatch>(serviceImpl.GetPendingCommands));
      serviceBinder.AddMethod(__Method_GetManualControls, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.ManualControlRequest, global::MIMISK.Grpc.ManualControlBatch>(serviceImpl.GetManualControls));
      serviceBinder.AddMethod(__Method_GetExternalReferences, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.ExternalReferenceRequest, global::MIMISK.Grpc.ExternalReferenceBatch>(serviceImpl.GetExternalReferences));
      serviceBinder.AddMethod(__Method_ReportCommandResult, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MIMISK.Grpc.CommandExecutionResult, global::MIMISK.Grpc.TelemetryAck>(serviceImpl.ReportCommandResult));
    }

  }
}
#endregion
